# Generated by Django 4.0 on 2025-04-30 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashflow',
            name='status',
        ),
        migrations.AddField(
            model_name='cashflow',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='flows', to='dds.status', verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
